### ISSUE TITLE
DbfReader throws error when trying to parse NULL Date fields

### ISSUE THREAD

**Issue by kyleeinspahr** [NetTopologySuite/NetTopologySuite.IO.Esri#61]
When evaluating the DbfReader Enumerable of a shapefile that has a Date column with NULL values, it throws the following error:
`The DateTime represented by the string '00000000' is not supported in calendar 'System.Globalization.GregorianCalendar'.`

Before that, I examined the Fields collection and it even reports that the Value is null:
![image](https://github.com/user-attachments/assets/0f5fafa1-c59b-4805-8527-5a21ab478a36)

Here is a file that shows the issue
[ShapefileWithNULLDate.zip](https://github.com/user-attachments/files/17602515/ShapefileWithNULLDate.zip)

**Comment by KubaSzostak** [comment]
Hi @kyleeinspahr, I checked the `ShapefileWithNULLDate.shp` file using following code and everything works fine. Can you provide a sample code that demonstrates the issue?

```cs
var shpPath = TestShapefiles.PathTo("Issues/061/ShapefileWithNULLDate.shp");
using var shpReader = Shapefile.OpenRead(shpPath);

while (shpReader.Read())
{
    var smapleId = shpReader.Fields["SAMPLEID"].Value ?? "<null>";
    var eventDate = shpReader.Fields["EVENT_DATE"].Value ?? "<null>";
    Console.WriteLine($"SAMPLEID: {smapleId},   EVENT_DATE: {eventDate}");
}
```

Output:

```terminal
SAMPLEID: 1,   EVENT_DATE: <null>
SAMPLEID: 2,   EVENT_DATE: <null>
SAMPLEID: 3,   EVENT_DATE: <null>
SAMPLEID: 4,   EVENT_DATE: <null>
SAMPLEID: 5,   EVENT_DATE: <null>
```

**Comment by jeroenvheel** [comment]
We also got a issue with 'System.Globalization.GregorianCalendar' => The DateTime represented by the string '20220025' is not supported in calendar 'System.Globalization.GregorianCalendar

We dont read the field in question 'OBJECT_BEG' and still we get a error.

````c#
var shpPath = TestShapefiles.PathTo("2024_03_01_Natuurlijke_beplanting_Almere.shp");
using var shpReader = Shapefile.OpenRead(shpPath);

while (shpReader.Read())
{
    var obj_guid = shpReader.Fields["OBJECT_GUI"].Value ?? "<null>";
    var std_domain = shpReader.Fields["STD_DOMEIN"].Value ?? "<null>";
    Console.WriteLine($"GUID: {obj_guid},   Domain: {std_domain}");
}
````

the file size is ~50mb so i uploaded it to my own cloud.
https://jeroenvheel.stackstorage.com/s/C9HewyqF9So2i5Fd


````
System.FormatException: The DateTime represented by the string '20220025' is not supported in calendar 'System.Globalization.GregorianCalendar'.
   at System.DateTime.ParseExact(String s, String format, IFormatProvider provider)
   at NetTopologySuite.IO.Esri.Dbf.Fields.DbfDateField.ReadValue(Stream stream)
   at NetTopologySuite.IO.Esri.Dbf.DbfReader.Read(Boolean& deleted)
   at NetTopologySuite.IO.Esri.Shapefiles.Readers.ShapefileReader`1.Read(Boolean& deleted)
   at NetTopologySuite.IO.Esri.Shapefiles.Readers.ShapefileReader.Read()
